/**
 * Service worker registration stub. Phase 1 ships a manifest so the app is
 * installable as a PWA shell, but does not yet register a real worker. We
 * keep the function exported so wiring an actual worker is a one-line change
 * later.
 */
export function registerServiceWorker(): void {
  if (typeof window === 'undefined') return;
  if (!('serviceWorker' in navigator)) return;
  // Intentionally a no-op for Phase 1. A future feature will register
  // a proper worker generated by vite-plugin-pwa or a hand-rolled file.
}
