steps:
  # Clone and checkout to ansible repository
  # - name: gcr.io/cloud-builders/git
  #   args:
  #     - clone
  #     - "git@github.com:simple-org/y.git"
  #     - "shared-ansible"
  #   dir: "./ansible"

  - name: gcr.io/cloud-builders/git
    args:
      - checkout
      - main

  # Docker Build
  # - name: "gcr.io/cloud-builders/docker"
  #   args:
  #     [
  #       "build",
  #       "-t",
  #       "us-central1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/myimage",
  #       ".",
  #     ]
  #
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
# availableSecrets:
#   secretManager:
#     - versionName: projects/523250825015/secrets/github-connection-github-oauthtoken-e16fd9/versions/1
#       env: "SSH_KEY"
# dependencies:
#   # - repository: "projects/lapakgaming-dev/localtions/global/connections/github-connections/repositories/lapakgaming/ansible"
#   - gitSource:
#       repository:
#         url: https://github.com/simple-org/y.git
#         developerConnect: projects/lapakgaming-dev/locations/asia-southeast2/connections/simple-org/gitRepositoryLinks/simple-org-x-y
#       revision: master
#       recurseSubmodules: true
#       depth: 1
#       destPath: ansible-repo
